### ISSUE TITLE
package.json vue 1.0.15?

### ISSUE THREAD

**Issue by phtwo** [MeCKodo/vue-multipage#10]
看到你有个提交写到使用 vue2

**Comment by MeCKodo** [comment]
因为vue这样的第三方是直接在html页面script引入得，入口文件不用import vue。我package忘记更新了，还有那个vue-loader也得更新下，我记得vue2对loader有要求。

**Comment by phtwo** [comment]
@MeCKodo 这就是我不明白的地方，为什么不在入口 import vue？

**Comment by MeCKodo** [comment]
如果只有一个index的话，那修改了别的就不会被缓存了啊，第三方库都应该直接script标签写然后带cdn，被缓存
