### ISSUE TITLE
请问vue版本是2.0吗？

### ISSUE THREAD

**Issue by kukujbb** [MeCKodo/vue-multipage#12]
package.json里面看到vue的版本是1？？

**Comment by MeCKodo** [comment]
你看readme，第三方的库直接script引入比较好，这样可以直接CDN缓存。就不用在意package里的vue版本

**Comment by kukujbb** [comment]
好的 十分感谢 还有个小问题 在引入UI框架的时候 失败 请问您是怎么解决的？谢谢

**Comment by MeCKodo** [comment]
我平时是不用UI框架的，所以很少用到各种UI框架。如果是bootstrap单纯的CSS我试过直接入口js文件
import bootstrap/dist/css/xxx  这样。
具体还是得根据报什么错才能知道什么问题

**Comment by kukujbb** [comment]
![1485080907 1](https://cloud.githubusercontent.com/assets/20284294/22181872/abf57072-e0d0-11e6-9bfe-87142b36170a.png)
您可以试试 就提示找不到模块
