### ISSUE TITLE
yourCDNLink

### ISSUE THREAD

**Issue by elva2596** [MeCKodo/vue-multipage#17]
你好，在最后build的时候，yourCDNLink指的是什么呢？因为我项目是基于多静态页面+es6开发，想使用你的配置环境来编写，因为后期我的静态页面要给java后台做模板使用，此处的cdn连接是指java后台的服务端地址吗？

**Comment by MeCKodo** [comment]
是静态资源的地址，如果静态资源有放在CDN就放在CDN上，也可以算是webpack中的publicPath
