### ISSUE TITLE
run dev能否强制整站编译一次

### ISSUE THREAD

**Issue by mackxu** [MeCKodo/vue-multipage#5]
原由：
1. 手动删除了static下的某个文件夹，run dev命令后查看目录，没有生成被删除的文件夹
2. static文件夹下会残留不需要的文件(如js文件夹下**重命名**或**删除**某个js文件)

期待：
1. 第一次dev时，清空static文件夹，整站重新编译一次
或
2. 同1，dev ＋ 参数

好处是：
1. 没有watch情况下的修改，也能在下一次run dev编译生效
2. static下没有残留文件

注：
static 是src/static
js 是 src/js

**Comment by MeCKodo** [comment]
当初有考虑过这个问题，但是我不希望dev启动时间要等很久。所以static下的文件本不应该删除的，删除了在编译删去的文件其实就好，这样每次可以节省更多时间。
我在近期会找时间升级，成功的话会废除src下的static，敬请期待。

**Comment by mackxu** [comment]
如果是启动时间的考虑，建议可以添加个新的命令，用来清空static + 编译一次。

希望能有帮助

**Comment by MeCKodo** [comment]
好的，十分感谢你的建议
